
/* ============================= İÇERİK VERİSİ (A1) ============================= */

const VOCAB = [
["gun","gün/ay","luni","pazartesi"],["gun","gün/ay","marți","salı"],["gun","gün/ay","miercuri","çarşamba"],
["gun","gün/ay","joi","perşembe"],["gun","gün/ay","vineri","cuma"],["gun","gün/ay","sâmbătă","cumartesi"],
["gun","gün/ay","duminică","pazar"],["gun","gün/ay","ianuarie","ocak (ay)"],["gun","gün/ay","februarie","şubat"],
["gun","gün/ay","martie","mart"],["gun","gün/ay","aprilie","nisan"],["gun","gün/ay","mai","mayıs"],
["gun","gün/ay","iunie","haziran"],["gun","gün/ay","iulie","temmuz"],["gun","gün/ay","august","ağustos"],
["gun","gün/ay","septembrie","eylül"],["gun","gün/ay","octombrie","ekim"],["gun","gün/ay","noiembrie","kasım"],
["gun","gün/ay","decembrie","aralık"],["gun","gün/ay","sfert","çeyrek"],["gun","gün/ay","jumătate","yarım"],["gun","gün/ay","fix","tam"],
["hava","hava durumu","cald","sıcak"],["hava","hava durumu","frig","soğuk"],["hava","hava durumu","soare","güneş"],
["hava","hava durumu","vânt","rüzgar"],["hava","hava durumu","zăpadă","kar"],["hava","hava durumu","nori","bulutlar"],
["hava","hava durumu","a ploua","yağmur yağmak"],["hava","hava durumu","a ninge","kar yağmak"],
["aile","aile","mamă","anne"],["aile","aile","tată","baba"],["aile","aile","bunic","büyükbaba"],["aile","aile","bunică","büyükanne"],
["aile","aile","fiu","oğul"],["aile","aile","fiică","kız evlat"],["aile","aile","frate","erkek kardeş"],["aile","aile","soră","kız kardeş"],
["aile","aile","unchi","amca/dayı"],["aile","aile","mătușă","teyze/hala"],["aile","aile","verișor","kuzen"],["aile","aile","nepot","yeğen/torun"],
["kimlik","kişisel bilgi","stradă","sokak"],["kimlik","kişisel bilgi","oraș","şehir"],
["kimlik","kişisel bilgi","sat","köy"],["kimlik","kişisel bilgi","țară","ülke"],["kimlik","kişisel bilgi","pașaport","pasaport"],
["kimlik","kişisel bilgi","carte de identitate","kimlik kartı"],
["ozellik","kişisel özellikler","înalt","uzun boylu"],["ozellik","kişisel özellikler","slab","zayıf"],["ozellik","kişisel özellikler","frumos","güzel"],
["ozellik","kişisel özellikler","blond","sarışın"],["ozellik","kişisel özellikler","brunet","esmer"],["ozellik","kişisel özellikler","bun","iyi"],
["ozellik","kişisel özellikler","rău","kötü"],["ozellik","kişisel özellikler","harnic","çalışkan"],["ozellik","kişisel özellikler","leneș","tembel"],
["ozellik","kişisel özellikler","inteligent","zeki"],["ozellik","kişisel özellikler","elegant","şık"],["ozellik","kişisel özellikler","sportiv","sportif"],
["egitim","eğitim","școală","okul"],["egitim","eğitim","facultate","fakülte"],["egitim","eğitim","student","öğrenci"],
["egitim","eğitim","curs","ders"],["egitim","eğitim","pauză","teneffüs"],
["meslek","meslekler","profesor","öğretmen"],["meslek","meslekler","doctor","doktor"],["meslek","meslekler","asistentă medicală","hemşire"],
["meslek","meslekler","farmacist","eczacı"],["meslek","meslekler","inginer","mühendis"],["meslek","meslekler","pictor","ressam"],
["meslek","meslekler","polițist","polis"],["meslek","meslekler","actor","aktör"],["meslek","meslekler","chelner","garson"],
["meslek","meslekler","șofer","şoför"],["meslek","meslekler","vânzător","satıcı"],["mekan","şehir mekanları","birou","ofis"],
["meslek","meslekler","coleg","meslektaş"],["meslek","meslekler","avocat","avukat"],["meslek","meslekler","pensionar","emekli"],
["vucut","vücut/sağlık","cap","baş"],["vucut","vücut/sağlık","gât","boyun"],["vucut","vücut/sağlık","păr","saç"],
["vucut","vücut/sağlık","ochi","göz"],["vucut","vücut/sağlık","nas","burun"],["vucut","vücut/sağlık","ureche","kulak"],
["vucut","vücut/sağlık","gură","ağız"],["vucut","vücut/sağlık","dinți","dişler"],["vucut","vücut/sağlık","mână","el"],
["vucut","vücut/sağlık","picior","ayak/bacak"],["vucut","vücut/sağlık","corp","vücut"],["vucut","vücut/sağlık","piele","cilt"],
["vucut","vücut/sağlık","pastă de dinți","diş macunu"],["vucut","vücut/sağlık","săpun","sabun"],["vucut","vücut/sağlık","șampon","şampuan"],
["vucut","vücut/sağlık","prosop","havlu"],["vucut","vücut/sağlık","medicament","ilaç"],
["giyim","giyim/aksesuar","pantaloni","pantolon"],["giyim","giyim/aksesuar","bluză","bluz"],["giyim","giyim/aksesuar","cămașă","gömlek"],
["giyim","giyim/aksesuar","tricou","tişört"],["giyim","giyim/aksesuar","pulover","kazak"],["giyim","giyim/aksesuar","fustă","etek"],
["giyim","giyim/aksesuar","rochie","elbise"],["giyim","giyim/aksesuar","căciulă","bere"],["giyim","giyim/aksesuar","mănuși","eldiven"],
["giyim","giyim/aksesuar","pantofi","ayakkabı"],["giyim","giyim/aksesuar","sandale","sandalet"],["giyim","giyim/aksesuar","ghete","bot"],
["giyim","giyim/aksesuar","cizme","çizme"],["giyim","giyim/aksesuar","geantă","çanta"],["giyim","giyim/aksesuar","rucsac","sırt çantası"],
["giyim","giyim/aksesuar","cravată","kravat"],["giyim","giyim/aksesuar","ceas","saat"],["giyim","giyim/aksesuar","inel","yüzük"],
["renk","renkler","alb","beyaz"],["renk","renkler","negru","siyah"],["renk","renkler","galben","sarı"],["renk","renkler","albastru","mavi"],
["renk","renkler","roșu","kırmızı"],["renk","renkler","verde","yeşil"],
["konut","konut","casă","ev"],["konut","konut","apartament","daire"],["konut","konut","bloc","apartman"],["konut","konut","grădină","bahçe"],
["konut","konut","curte","avlu"],["konut","konut","cameră de zi","oturma odası"],["konut","konut","bucătărie","mutfak"],
["konut","konut","dormitor","yatak odası"],["konut","konut","baie","banyo"],["konut","konut","hol","hol"],
["konut","konut","masă","masa"],["konut","konut","scaun","sandalye"],["konut","konut","dulap","dolap"],["konut","konut","pat","yatak"],
["konut","konut","canapea","kanepe"],["konut","konut","frigider","buzdolabı"],["konut","konut","aragaz","ocak (aragaz)"],
["konut","konut","mașină de spălat","çamaşır makinesi"],["konut","konut","farfurie","tabak"],["konut","konut","pahar","bardak"],
["konut","konut","lingură","kaşık"],["konut","konut","furculiță","çatal"],["konut","konut","cuțit","bıçak"],
["yiyecek","yiyecek/içecek","mic dejun","kahvaltı"],["yiyecek","yiyecek/içecek","prânz","öğle yemeği"],["yiyecek","yiyecek/içecek","cină","akşam yemeği"],
["yiyecek","yiyecek/içecek","ciorbă","çorba"],["yiyecek","yiyecek/içecek","cartof","patates"],["yiyecek","yiyecek/içecek","orez","pirinç"],
["yiyecek","yiyecek/içecek","salată","salata"],["yiyecek","yiyecek/içecek","omletă","omlet"],["yiyecek","yiyecek/içecek","sendviș","sandviç"],
["yiyecek","yiyecek/içecek","pâine","ekmek"],["yiyecek","yiyecek/içecek","lapte","süt"],["yiyecek","yiyecek/içecek","iaurt","yoğurt"],
["yiyecek","yiyecek/içecek","brânză","peynir"],["yiyecek","yiyecek/içecek","unt","tereyağı"],["yiyecek","yiyecek/içecek","roșie","domates"],
["yiyecek","yiyecek/içecek","castravete","salatalık"],["yiyecek","yiyecek/içecek","ceapă","soğan"],["yiyecek","yiyecek/içecek","morcov","havuç"],
["yiyecek","yiyecek/içecek","măr","elma"],["yiyecek","yiyecek/içecek","banană","muz"],["yiyecek","yiyecek/içecek","portocală","portakal"],
["yiyecek","yiyecek/içecek","pui","tavuk"],["yiyecek","yiyecek/içecek","porc","domuz"],["yiyecek","yiyecek/içecek","pește","balık"],
["yiyecek","yiyecek/içecek","zahăr","şeker"],["yiyecek","yiyecek/içecek","ciocolată","çikolata"],["yiyecek","yiyecek/içecek","înghețată","dondurma"],
["yiyecek","yiyecek/içecek","apă","su"],["yiyecek","yiyecek/içecek","ceai","çay"],["yiyecek","yiyecek/içecek","cafea","kahve"],
["yiyecek","yiyecek/içecek","suc","meyve suyu"],["yiyecek","yiyecek/içecek","vin","şarap"],["yiyecek","yiyecek/içecek","bere","bira"],
["yiyecek","yiyecek/içecek","sare","tuz"],["yiyecek","yiyecek/içecek","piper","biber"],
["gunluk","günlük aktivite","a se trezi","uyanmak"],["gunluk","günlük aktivite","a se spăla","yıkanmak"],["gunluk","günlük aktivite","a se îmbrăca","giyinmek"],
["gunluk","günlük aktivite","a mânca","yemek yemek"],["gunluk","günlük aktivite","a lucra","çalışmak"],["gunluk","günlük aktivite","a studia","ders çalışmak"],
["gunluk","günlük aktivite","a găti","yemek pişirmek"],["gunluk","günlük aktivite","a se culca","yatmaya gitmek"],
["spor","spor/boş zaman","fotbal","futbol"],["spor","spor/boş zaman","baschet","basketbol"],["spor","spor/boş zaman","tenis","tenis"],
["spor","spor/boş zaman","înot","yüzme"],["spor","spor/boş zaman","a alerga","koşmak"],["spor","spor/boş zaman","a dansa","dans etmek"],
["spor","spor/boş zaman","a se plimba","yürüyüş yapmak"],["spor","spor/boş zaman","a citi","okumak"],["spor","spor/boş zaman","a se juca","oynamak"],
["spor","spor/boş zaman","a vizita","ziyaret etmek"],["spor","spor/boş zaman","a călători","seyahat etmek"],["spor","spor/boş zaman","a picta","resim yapmak"],
["tatil","tatil","mare","deniz"],["tatil","tatil","munte","dağ"],["tatil","tatil","lac","göl"],["tatil","tatil","hotel","otel"],
["tatil","tatil","muzeu","müze"],["tatil","tatil","biserică","kilise"],
["ulasim","ulaşım","bicicletă","bisiklet"],["ulasim","ulaşım","mașină","araba"],["ulasim","ulaşım","taxi","taksi"],
["ulasim","ulaşım","autobuz","otobüs"],["ulasim","ulaşım","tren","tren"],["ulasim","ulaşım","metrou","metro"],
["ulasim","ulaşım","avion","uçak"],["ulasim","ulaşım","stație","durak"],["ulasim","ulaşım","gară","tren istasyonu"],
["ulasim","ulaşım","aeroport","havalimanı"],["ulasim","ulaşım","bilet","bilet"],
["doga","doğa","câine","köpek"],["doga","doğa","pisică","kedi"],["doga","doğa","vacă","inek"],["doga","doğa","cal","at"],
["doga","doğa","copac","ağaç"],["doga","doğa","floare","çiçek"],["doga","doğa","iarbă","çimen"],
["sehir","şehir mekanları","magazin","mağaza"],["sehir","şehir mekanları","preț","fiyat"],["sehir","şehir mekanları","scump","pahalı"],
["sehir","şehir mekanları","ieftin","ucuz"],["sehir","şehir mekanları","a cumpăra","satın almak"],["sehir","şehir mekanları","a vinde","satmak"],
["sehir","şehir mekanları","restaurant","restoran"],["sehir","şehir mekanları","meniu","menü"],["sehir","şehir mekanları","a comanda","sipariş vermek"],
["sehir","şehir mekanları","a plăti","ödemek"],["sehir","şehir mekanları","spital","hastane"],["sehir","şehir mekanları","farmacie","eczane"],
["sehir","şehir mekanları","bancă","banka"],["sehir","şehir mekanları","bani","para"],["sehir","şehir mekanları","poștă","postane"],
["sehir","şehir mekanları","bibliotecă","kütüphane"],["sehir","şehir mekanları","carte","kitap"],
["medya","basın/medya","ziar","gazete"],["medya","basın/medya","revistă","dergi"],["medya","basın/medya","televizor","televizyon"],["medya","basın/medya","radio","radyo"],
["zamir","zamirler","eu","ben"],["zamir","zamirler","tu","sen"],["zamir","zamirler","el","o (erkek)"],["zamir","zamirler","ea","o (kadın)"],
["zamir","zamirler","noi","biz"],["zamir","zamirler","voi","siz"],["zamir","zamirler","ei","onlar (erkek)"],["zamir","zamirler","ele","onlar (kadın)"],
["soru","soru kelimeleri","ce","ne"],["soru","soru kelimeleri","cine","kim"],["soru","soru kelimeleri","unde","nerede"],
["soru","soru kelimeleri","cum","nasıl"],["soru","soru kelimeleri","când","ne zaman"],["soru","soru kelimeleri","care","hangi"],["soru","soru kelimeleri","de ce","neden"],
["baglac","bağlaçlar","și","ve"],["baglac","bağlaçlar","dar","ama"],["baglac","bağlaçlar","sau","veya"],["baglac","bağlaçlar","pentru că","çünkü"],
["zaman","zaman zarfları","acum","şimdi"],["zaman","zaman zarfları","azi","bugün"],["zaman","zaman zarfları","ieri","dün"],
["zaman","zaman zarfları","mâine","yarın"],["zaman","zaman zarfları","mereu","her zaman"],["zaman","zaman zarfları","niciodată","hiçbir zaman"],
["yer","yer zarfları","aici","burada"],["yer","yer zarfları","acolo","orada"],["yer","yer zarfları","sus","yukarıda"],["yer","yer zarfları","jos","aşağıda"],
];
const THEME_NAMES = {gun:"Gün/Ay/Saat",hava:"Hava Durumu",aile:"Aile",kimlik:"Kişisel Bilgi",ozellik:"Kişisel Özellikler",
egitim:"Eğitim",meslek:"Meslekler",vucut:"Vücut/Sağlık",giyim:"Giyim/Aksesuar",renk:"Renkler",konut:"Konut",
yiyecek:"Yiyecek/İçecek",gunluk:"Günlük Aktivite",spor:"Spor/Boş Zaman",tatil:"Tatil",ulasim:"Ulaşım",doga:"Doğa",
sehir:"Şehir Mekanları",medya:"Basın/Medya",zamir:"Zamirler",soru:"Soru Kelimeleri",baglac:"Bağlaçlar",zaman:"Zaman Zarfları",yer:"Yer Zarfları"};

// fiil: [ro, tr, [eu,tu,el,noi,voi,ei], participiu, grup]
const VERBS = [
["a fi","olmak",["sunt","ești","este","suntem","sunteți","sunt"],"fost","Düzensiz"],
["a avea","sahip olmak",["am","ai","are","avem","aveți","au"],"avut","Düzensiz"],
["a putea","yapabilmek",["pot","poți","poate","putem","puteți","pot"],"putut","Düzensiz"],
["a vrea","istemek",["vreau","vrei","vrea","vrem","vreți","vor"],"vrut","Düzensiz"],
["a ști","bilmek",["știu","știi","știe","știm","știți","știu"],"știut","Düzensiz"],
["a da","vermek",["dau","dai","dă","dăm","dați","dau"],"dat","Düzensiz"],
["a lua","almak",["iau","iei","ia","luăm","luați","iau"],"luat","Düzensiz"],
["a veni","gelmek",["vin","vii","vine","venim","veniți","vin"],"venit","Düzensiz"],
["a merge","gitmek",["merg","mergi","merge","mergem","mergeți","merg"],"mers","Düzensiz"],
["a sta","oturmak/kalmak",["stau","stai","stă","stăm","stați","stau"],"stat","Düzensiz"],
["a mânca","yemek yemek",["mănânc","mănânci","mănâncă","mâncăm","mâncați","mănâncă"],"mâncat","Düzensiz"],
["a bea","içmek",["beau","bei","bea","bem","beți","beau"],"băut","-E grubu"],
["a vedea","görmek",["văd","vezi","vede","vedem","vedeți","văd"],"văzut","-EA grubu"],
["a face","yapmak",["fac","faci","face","facem","faceți","fac"],"făcut","-E grubu"],
["a scrie","yazmak",["scriu","scrii","scrie","scriem","scrieți","scriu"],"scris","-E grubu"],
["a spune","söylemek",["spun","spui","spune","spunem","spuneți","spun"],"spus","-E grubu"],
["a crede","inanmak",["cred","crezi","crede","credem","credeți","cred"],"crezut","-E grubu"],
["a duce","götürmek",["duc","duci","duce","ducem","duceți","duc"],"dus","-E grubu"],
["a aduce","getirmek",["aduc","aduci","aduce","aducem","aduceți","aduc"],"adus","-E grubu"],
["a deschide","açmak",["deschid","deschizi","deschide","deschidem","deschideți","deschid"],"deschis","-E grubu"],
["a închide","kapatmak",["închid","închizi","închide","închidem","închideți","închid"],"închis","-E grubu"],
["a răspunde","cevap vermek",["răspund","răspunzi","răspunde","răspundem","răspundeți","răspund"],"răspuns","-E grubu"],
["a înțelege","anlamak",["înțeleg","înțelegi","înțelege","înțelegem","înțelegeți","înțeleg"],"înțeles","-E grubu"],
["a începe","başlamak",["încep","începi","începe","începem","începeți","încep"],"început","-E grubu"],
["a plânge","ağlamak",["plâng","plângi","plânge","plângem","plângeți","plâng"],"plâns","-E grubu"],
["a citi","okumak",["citesc","citești","citește","citim","citiți","citesc"],"citit","-esc grubu"],
["a găsi","bulmak",["găsesc","găsești","găsește","găsim","găsiți","găsesc"],"găsit","-esc grubu"],
["a folosi","kullanmak",["folosesc","folosești","folosește","folosim","folosiți","folosesc"],"folosit","-esc grubu"],
["a iubi","sevmek",["iubesc","iubești","iubește","iubim","iubiți","iubesc"],"iubit","-esc grubu"],
["a munci","çalışmak (iş)",["muncesc","muncești","muncește","muncim","munciți","muncesc"],"muncit","-esc grubu"],
["a primi","almak/kabul etmek",["primesc","primești","primește","primim","primiți","primesc"],"primit","-esc grubu"],
["a vorbi","konuşmak",["vorbesc","vorbești","vorbește","vorbim","vorbiți","vorbesc"],"vorbit","-esc grubu"],
["a trăi","yaşamak",["trăiesc","trăiești","trăiește","trăim","trăiți","trăiesc"],"trăit","-esc grubu"],
["a servi","servis yapmak",["servesc","servești","servește","servim","serviți","servesc"],"servit","-esc grubu"],
["a locui","oturmak/yaşamak",["locuiesc","locuiești","locuiește","locuim","locuiți","locuiesc"],"locuit","-esc grubu"],
["a călători","seyahat etmek",["călătoresc","călătorești","călătorește","călătorim","călătoriți","călătoresc"],"călătorit","-esc grubu"],
["a plăti","ödemek",["plătesc","plătești","plătește","plătim","plătiți","plătesc"],"plătit","-esc grubu"],
["a găti","yemek pişirmek",["gătesc","gătești","gătește","gătim","gătiți","gătesc"],"gătit","-esc grubu"],
["a dormi","uyumak",["dorm","dormi","doarme","dormim","dormiți","dorm"],"dormit","-i grubu (basit)"],
["a fugi","kaçmak",["fug","fugi","fuge","fugim","fugiți","fug"],"fugit","-i grubu (basit)"],
["a auzi","duymak",["aud","auzi","aude","auzim","auziți","aud"],"auzit","-i grubu (basit)"],
["a împărți","paylaşmak",["împart","împarți","împarte","împărțim","împărțiți","împart"],"împărțit","-i grubu (basit)"],
["a lucra","çalışmak",["lucrez","lucrezi","lucrează","lucrăm","lucrați","lucrează"],"lucrat","-ez grubu"],
["a dansa","dans etmek",["dansez","dansezi","dansează","dansăm","dansați","dansează"],"dansat","-ez grubu"],
["a fuma","sigara içmek",["fumez","fumezi","fumează","fumăm","fumați","fumează"],"fumat","-ez grubu"],
["a vizita","ziyaret etmek",["vizitez","vizitezi","vizitează","vizităm","vizitați","vizitează"],"vizitat","-ez grubu"],
["a picta","resim yapmak",["pictez","pictezi","pictează","pictăm","pictați","pictează"],"pictat","-ez grubu"],
["a asculta","dinlemek",["ascult","asculți","ascultă","ascultăm","ascultați","ascultă"],"ascultat","-A grubu"],
["a întreba","sormak",["întreb","întrebi","întreabă","întrebăm","întrebați","întreabă"],"întrebat","-A grubu"],
["a cumpăra","satın almak",["cumpăr","cumperi","cumpără","cumpărăm","cumpărați","cumpără"],"cumpărat","-A grubu"],
["a alerga","koşmak",["alerg","alergi","aleargă","alergăm","alergați","aleargă"],"alergat","-A grubu"],
["a schimba","değiştirmek",["schimb","schimbi","schimbă","schimbăm","schimbați","schimbă"],"schimbat","-A grubu"],
["a pleca","gitmek/ayrılmak",["plec","pleci","pleacă","plecăm","plecați","pleacă"],"plecat","-A grubu"],
["a aștepta","beklemek",["aștept","aștepți","așteaptă","așteptăm","așteptați","așteaptă"],"așteptat","-A grubu"],
["a uita","unutmak",["uit","uiți","uită","uităm","uitați","uită"],"uitat","-A grubu"],
["a juca","oyun/spor oynamak",["joc","joci","joacă","jucăm","jucați","joacă"],"jucat","-A grubu"],
["a cânta","şarkı söylemek/çalgı çalmak",["cânt","cânți","cântă","cântăm","cântați","cântă"],"cântat","-A grubu"],
["a chema","çağırmak",["chem","chemi","cheamă","chemăm","chemați","cheamă"],"chemat","-A grubu"],
["a costa","fiyatı olmak",["cost","coști","costă","costăm","costați","costă"],"costat","-A grubu"],
];

/* Gramer alıştırma şablonları */
const PREP_ITEMS = [
["Eu sunt ___ Turcia.","în","Ben Türkiye'deyim.",["din","la","cu"]],
["Ea vine ___ România.","din","O Romanya'dan geliyor.",["în","pe","despre"]],
["Cartea este ___ masă.","pe","Kitap masanın üstünde.",["în","din","la"]],
["Noi vorbim ___ familie.","despre","Biz aile hakkında konuşuyoruz.",["cu","pe","din"]],
["El pleacă ___ ora 9.","la","O saat 9'da gidiyor.",["în","din","pentru"]],
["Cadoul este ___ tine.","pentru","Hediye senin için.",["cu","la","despre"]],
["Eu lucrez ___ Ana.","cu","Ben Ana ile çalışıyorum.",["fără","de la","până"]],
["Trenul pleacă ___ Cluj.","din","Tren Cluj'dan kalkıyor.",["la","pe","în"]],
];
const NEG_ITEMS = [
["Eu sunt acasă.","Eu nu sunt acasă."],
["Tu ai timp.","Tu nu ai timp."],
["Ei sunt aici.","Ei nu sunt aici."],
["Noi lucrăm azi.","Noi nu lucrăm azi."],
["Ea vine mâine.","Ea nu vine mâine."],
["Eu înțeleg.","Eu nu înțeleg."],
];
const QWORD_ITEMS = [
["___ ești?","De unde","Nerelisin?",["Cine","Cum","Ce"]],
["___ este acolo?","Cine","Orada kim var?",["Ce","Unde","Când"]],
["___ te cheamă?","Cum","Adın ne?",["Ce","Care","Cine"]],
["___ mergi la curs?","Când","Kursa ne zaman gidiyorsun?",["Unde","Cum","Cine"]],
["___ este cartea ta?","Care","Hangisi senin kitabın?",["Ce","Cine","Cum"]],
["___ pleci?","De ce","Neden gidiyorsun?",["Cum","Ce","Care"]],
];
/* sıfat: [isim, cinsiyet, sıfat-ERİL, sıfat-DİŞİL]
   SÜTUN SIRASI SABİTTİR: 3. sütun her zaman eril, 4. sütun her zaman dişil
   biçimdir — ismin cinsiyetine göre yer değiştirmez. (Eskiden dişil satırlarda
   "doğru cevap önce" mantığıyla ters yazılmıştı; exerciseForGrammar 4. sütunu
   dişil sandığı için uygulama "mașină nou", "casă mic", "fată frumos" gibi
   YANLIŞ biçimleri doğru cevap olarak veriyordu.)
   Nötr isimler tekilde eril gibi çekilir (un parc frumos), bu yüzden nötr
   satırlarda da doğru biçim 3. sütundur.
   İki sütunu aynı olan sıfat KULLANILMAZ (mare/mare gibi) — iki şık birebir
   aynı çıkar ve sorunun doğru cevabı ayırt edilemez. */
const ADJ_ITEMS = [
["copil","eril","mic","mică"],["casă","dişil","mic","mică"],["câine","eril","bun","bună"],
["floare","dişil","frumos","frumoasă"],["om","eril","înalt","înaltă"],["fată","dişil","frumos","frumoasă"],
["frate","eril","tânăr","tânără"],["mașină","dişil","nou","nouă"],["parc","nötr","frumos","frumoasă"],["carte","dişil","vechi","veche"],
];
/* [isim-yalın, cinsiyet, belirtili-doğru]
   Romencede üç cinsiyet vardır; parc/scaun/telefon NÖTR'dür (çoğulları
   parcuri/scaune/telefoane). Tekilde eril gibi çekildikleri için belirtili
   biçimleri -ul alır; "eril" diye etiketlemek çoğulu yanlış öğretiyordu. */
const ART_ITEMS = [
["copil","eril","copilul"],["parc","nötr","parcul"],["câine","eril","câinele"],
["casă","dişil","casa"],["cheie","dişil","cheia"],["mașină","dişil","mașina"],
["telefon","nötr","telefonul"],["scaun","nötr","scaunul"],["floare","dişil","floarea"],["stradă","dişil","strada"],
];
const NUM_ITEMS = [
["11","unsprezece"],["12","doisprezece"],["15","cincisprezece"],["20","douăzeci"],["21","douăzeci și unu"],
["30","treizeci"],["45","patruzeci și cinci"],["50","cincizeci"],["70","șaptezeci"],["100","o sută"],
];

const FIXED_SENTENCES = [
  ["Bine ați venit!","Hoş geldiniz!","sent_0"],
  ["Bine v-am găsit!","Hoş bulduk!","sent_1"],
  ["Bună dimineața!","Günaydın!","sent_2"],
  ["Bună ziua!","İyi günler!","sent_3"],
  ["Bună seara!","İyi akşamlar!","sent_4"],
  ["Cum te cheamă?","Senin adın ne?","sent_5"],
  ["Mă cheamă Arzu.","Benim adım Arzu.","sent_6"],
  ["De unde ești?","Nerelisin?","sent_7"],
  ["Eu sunt din Turcia, din Istanbul.","Ben Türkiye'denim, İstanbul'dan.","sent_8"],
  ["Ce faci?","Nasılsın?","sent_9"],
  ["Bine, mulțumesc!","İyi, teşekkür ederim!","sent_10"],
  ["Îmi pare bine!","Memnun oldum!","sent_11"],
  ["Eu sunt aici.","Ben buradayım.","sent_12"],
  ["Tu ești acolo.","Sen oradasın.","sent_13"],
  ["Noi suntem în parc.","Biz parktayız.","sent_14"],
  ["Voi sunteți în casă.","Siz evdesiniz.","sent_15"],
  ["Eu sunt la telefon.","Ben telefondayım.","sent_16"],
  ["Noi suntem la curs.","Biz kurstayız.","sent_17"],
  ["Eu sunt acasă.","Evimdeyim.","sent_18"],
  ["Eu sunt aici?","Ben burada mıyım?","sent_19"],
  ["Tu ești acolo?","Sen orada mısın?","sent_20"],
  ["El este acasă?","O evde mi?","sent_21"],
  ["Noi nu suntem aici.","Biz burada değiliz.","sent_22"],
  ["Voi nu sunteți în casă.","Siz evde değilsiniz.","sent_23"],
  ["Ei nu sunt acolo.","Onlar orada değiller.","sent_24"],
  ["Eu sunt aici acum.","Ben şimdi buradayım.","sent_25"],
  ["Tu ești acolo astăzi.","Sen bugün oradasın.","sent_26"],
  ["Eu sunt aici, dar tu ești acolo.","Ben buradayım ama sen oradasın.","sent_27"],
  ["Tu ești la curs și eu sunt la telefon.","Sen kurstasın ve ben telefondayım.","sent_28"],
  ["Voi sunteți în România, dar noi suntem în Turcia.","Siz Romanya'dasınız ama biz Türkiye'deyiz.","sent_29"],
  ["Astăzi eu nu sunt acasă.","Bugün evde değilim.","sent_30"],
  ["Voi sunteți la curs acum.","Siz şimdi kurstasınız.","sent_31"],
  ["Tu ești în România?","Sen Romanya'da mısın?","sent_32"],
  ["Ali nu este acum aici, dar Ayșe este aici.","Ali şimdi burada değil ama Ayşe burada.","sent_33"],
  ["Eu sunt mereu aici, dar tu nu ești niciodată acasă.","Ben her zaman buradayım ama sen hiçbir zaman evde değilsin.","sent_34"],
  ["Eu am timp.","Benim zamanım var.","sent_35"],
  ["Tu ai timp.","Senin zamanın var.","sent_36"],
  ["Noi nu avem cafea.","Bizim kahvemiz yok.","sent_37"],
  ["Voi aveți mașină?","Sizin arabanız var mı?","sent_38"],
  ["Tu nu ai niciodată bani.","Senin hiçbir zaman paran yok.","sent_39"],
  ["Eu am plâns azi.","Ben bugün ağladım.","sent_40"],
  ["Voi ați înțeles?","Siz anladınız mı?","sent_41"],
  ["Da, eu am înțeles.","Evet, ben anladım.","sent_42"],
  ["Noi am început acum.","Biz şimdi başladık.","sent_43"],
  ["Eu am terminat.","Ben bitirdim.","sent_44"],
  ["Eu nu am făcut nimic azi.","Ben bugün hiçbir şey yapmadım.","sent_45"],
  ["Noi am mâncat mult în restaurant ieri.","Biz dün restoranda çok yedik.","sent_46"],
  ["Voi ați auzit ceva?","Bir şey duydunuz mu?","sent_47"],
  ["Noi nu am auzit nimic.","Hiçbir şey duymadık.","sent_48"],
  ["Am plecat acasă ieri.","Ben dün eve gittim.","sent_49"],
  ["Domnul Ali a vorbit mult la telefon.","Ali Bey telefonda çok konuştu.","sent_50"],
  ["Tu ai înțeles ceva?","Sen bir şey anladın mı?","sent_51"],
  ["Noi am răspuns bine.","Biz iyi cevapladık.","sent_52"],
  ["Eu am băut cafea în România.","Romanya'da kahve içtim.","sent_53"],
  ["Noi am băut ceai în Turcia.","Türkiye'de çay içtik.","sent_54"],
  ["Azi nu am mâncat ciorbă, dar am băut apă.","Bugün çorba yemedim ama su içtim.","sent_55"],
  ["Care este numele tău?","Adın nedir?","sent_56"],
  ["Cine este în casă?","Kim evde?","sent_57"],
  ["Când sunteți la curs?","Ne zaman kurstasınız?","sent_58"],
];
